apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: pro_frontend
  description: |
    No description provided
  annotations:
    github.com/project-slug: Meeranmk/pro_frontend
  links:
    - title: Repository
      url: https://github.com/Meeranmk/pro_frontend
spec:
  type: service
  lifecycle: production
  owner: user:Meeranmk
